name: Daily scraper of DoJ Capitol Breach Cases

on:
  workflow_dispatch:
  schedule:
    - cron: '27 19 * * *'

jobs:
  scheduled:
    runs-on: macOS-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup R
      uses: r-lib/actions/setup-r@v2

    - name: Process DoJ Case Data
      run: R --silent --no-echo --file=doj-case-scraper.R

    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Update data: ${timestamp}" || exit 0
        git push
        
