name: Visualize latest DMARC run

on:
  workflow_dispatch:
  schedule:
    - cron: '27 19 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Install Ubuntu dependencies
      run: sudo apt install -y libcurl4-openssl-dev libgmp-dev libxml2-dev libglpk-dev

    - name: Setup R
      uses: r-lib/actions/setup-r@v1
      with:
        r-version: "4.1.0"
        http-user-agent: "R/4.1.0 R (4.1.0 x86_64-pc-linux-gnu x86_64 linux-gnu)"

    - name: Process DMARC Data
      run: R --silent --no-echo --file=doj-case-scraper.R

    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Update data: ${timestamp}" || exit 0
        git push